### ISSUE TITLE
Update to Heroicons v2

### ISSUE THREAD

**Issue by driesvints** [laravelio/paste.laravel.io#122]
We'll need to make sure all icons still work as some have gotten different names.

**Comment by thinkverse** [comment]
Have a working branch locally, and wanted to get your opinion on how which icons to use. The menu bar and x icon look pretty much the same. The save button is drastically different, and the reset icon looks also pretty much the same just thinner.

![Screen Shot 2022-09-09 at 12 45 06 AM](https://user-images.githubusercontent.com/2221746/189239334-50da75d4-14e5-4097-a15b-38b88271dbed.png)

Maybe go with the document plus one instead? Seems more uniform in v2, or perhaps folder plus?

![Screen Shot 2022-09-09 at 12 54 12 AM](https://user-images.githubusercontent.com/2221746/189240193-d43c2198-08e5-47c7-b13d-9fc77347e2e3.png)

![Screen Shot 2022-09-09 at 12 57 14 AM](https://user-images.githubusercontent.com/2221746/189240212-0ae79468-2cfe-4af8-a4fd-8fd4f39cca4c.png)

**Comment by driesvints** [comment]
@thinkverse yes. I agree, feel free to update that and ping me. Thanks!
