### ISSUE TITLE
Drag/Drop File Support

### ISSUE THREAD

**Issue by PR3SIDENT** [laravelio/paste.laravel.io#161]
Hey guys, I feel really lucky to have found this project. I am looking to use this for some upcoming needs but wondered, can you allow for support to drag/drop or even have a button to "Upload" a text file for people less inclined, or more error prone? Copy/Pasting log files can be tricky to the not-so-inclined user.

**Comment by driesvints** [comment]
Hey there, thanks for your suggestion but right now we’re not planning on doing any file hosting.
