### ISSUE TITLE
Create a simple API

### ISSUE THREAD

**Issue by driesvints** [laravelio/paste.laravel.io#18]
@RobinMalfait commented on [Wed Sep 10 2014](https://github.com/laravelio/portal/issues/177)

That way we can create plugins for Sublime Text, Phpstorm, ... :)

---

@driesvints commented on [Wed Sep 10 2014](https://github.com/laravelio/portal/issues/177#issuecomment-55177924)

Thanks for the suggestion :)

Also not a priority but feel free to offer some input on how you'd like to see the api implemented.

**Comment by edcs** [comment]
Does it need any authentication? If not, a simple way of doing this would be to use  [`post()`](https://github.com/laravelio/pastebin/blob/master/app/Http/Controllers/PastesController.php#L15)
 and check the `Accept` header in to see if it's set to JSON. If it is, a JSON response should be returned and if not the standard redirect would be used.

The rate limiting middleware should be implemented to prevent abuse to begin with, reCaptcha or similar could be a future addition if needed.

**Comment by RobinMalfait** [comment]
@edcs I think that reCaptcha would be hard if you write plugins for IDE's and editors. A simple JSON api where you post and receive a link would be perfect. If you really want to prevent the spam though, I don't mind registering an "application" to retrieve some tokens to use in the headers.

I made plugins for PhpStorm & Sublime & VSCode in the past, so I do want to help create plugins for those!

**Comment by driesvints** [comment]
@edcs A simple POST & GET endpoint can be added to begin with. It should definitely be rate limited. It should always return JSON.

@RobinMalfait I'm not sure if we should start with whitelisting apps. Do you think that's necessary?

**Comment by RobinMalfait** [comment]
@driesvints whitelisting apps is not necessary. I was just thinking about preventing spam to use something like oauth. How would the rate limit work, do we need to register to get a token or do we need an /auth route first.

Or do we just use public POST & GET routes, and implement more security when needed?

**Comment by edcs** [comment]
@RobinMalfait: Rate limiting is already built into Laravel with the `\Illuminate\Routing\Middleware\ThrottleRequests::class` middleware. I'd say this is more than adequate for a project like this. If there's an abuse issue, fix it when it arises 🙂

**Comment by RobinMalfait** [comment]
@edcs perfect! We use an older version of Laravel, so I don't know much about all the latest and greatest goodies. Good to know though!

**Comment by driesvints** [comment]
@RobinMalfait yeah let's just go with the POST and GET route for now and see how it goes.

**Comment by driesvints** [comment]
I'm going to close this as I don't think this will ever land.
