### ISSUE TITLE
Upgrade to Tailwind CSS v3

### ISSUE THREAD

**Issue by driesvints** [laravelio/paste.laravel.io#92]
https://tailwindcss.com/docs/upgrade-guide

I can also buy a Tailwind CSS shift for us.

**Comment by juanabascal** [comment]
I've created a PR for this issue: https://github.com/laravelio/paste.laravel.io/pull/107.

I've just followed [Tailwind's official documentation](https://tailwindcss.com/docs/upgrade-guide) that @driesvints provided.
